---
title: "Monitoring African Urban Growth using Earth Observation"
subtitle: "LISS2113 EO Practical"
author:
  - name: José Gómez-Dans
    email: jose.gomez-dans@kcl.ac.uk
    orcid: 0000-0003-4787-8307
    affiliations:
      - name: King's College London
        department: Geography
        city: London
        country: UK
date: last-modified
---

# Welcome to the Urban Expansion Monitoring practical 

This practical is part of LISS 2113 (*Introduction to Geographic Information System and Spatial Data Analysis.*)

This practical will show you how to use optical Earth Observation data from the Landsat family of satellites to monitor urban expansion in West African cities. The practical uses Google Earth Engine to access the data and perform most of the tasks. 

::: {.callout-tip}
While GEE is now free to use for non commercial applications, the techniques are very general, and you can use them in other platforms/environments, and for other mapping/classification tasks.

:::



### Learning Objectives
By the end of this practical, you will have had experience in
* Access and filter large-scale satellite image collections (Landsat).
* Implement urban detection algorithms using JavaScript in GEE.
* Quantify spatial growth rates for a chosen city.
* Export publication-quality maps and data.

### Practical Structure
The workshop is divided into three main stages:

1.  **[Introduction](01-intro.qmd)**: Some background reading and other useful information.
2.  **[Data & methods](02-methods.qmd)**: A detailed description of the different tasks that you'll undertake.
3.  **[Build annual Landsat composite images](03-code.qmd)**: Use GEE to build annual base images that hopefully easily reflect different land cover types.
4.  **[Train, validate and apply a "Random Forest" classifier](04-classifier.qmd)**: Now, we'll use a machine learning method called "Random Forest" to build a classifier, validate that it works, and apply to our composite images
5.  **[Tracking urban growth. Discussion](05-discussion.qmd)**: Use your work to address a research question!

::: {.callout-important}

### Prerequisites

This practical assumes you have a Google Earth Engine account approved. If you do not, please notify the instructor immediately as approval can take a few days.
:::

### Further reading

This practical shows a typical application of EO data for research, but doesn't cover fundamental EO concepts, basics of statistics/Machine Learning, or even how to use Google Earth Engine. For that you'll need additional sources of information:

* Natural Resources Canada [Basics of Remote Sensing](https://www.nrcan.gc.ca/maps-tools-publications/satellite-imagery-air-photos/tutorial-fundamentals-remote-sensing/9309)
* NASA Applied Scinece [Fundamentals of Remote Sensing	ARSET](https://appliedsciences.nasa.gov/join-mission/training/english/fundamentals-remote-sensing)
* Lund University [Introduction to Remote Sensing and
Geographical Information Systems](https://www.nateko.lu.se/sites/nateko.lu.se.sv/files/remote_sensing_and_gis_20111212.pdf)
* Random forest in remote sensing: A review of applications and future directions [Belgiu and Dragut (2016)](https://doi.org/10.1016/j.isprsjprs.2016.01.011)
* [Getting started with Google Earth Engine](https://developers.google.com/earth-engine/guides/getstarted)
* [GEE community tutorials](https://developers.google.com/earth-engine/tutorials)
* [GEE Javascript API](https://developers.google.com/earth-engine/tutorials/tutorial_api_01)

### Getting Help
If you get stuck during the code blocks:

* Use Search Engines!! 
* Check the **Console** for specific error messages.
* Use the `print()` function to inspect variables.
* Reference the [Official GEE Documentation](https://developers.google.com/earth-engine/guides).

**If you are happy using Large Language Models (LLMs)**, you can get a lot of very uesful help from them:
* You can ask the LLM to "Explain this code to me in really simple terms"
* Modify the code to e.g. use Python rather than Javascript if you see it fit
* Explore additional datasets 